---
name: Test the Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  container-build:
    name: Build the container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build the container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: "otel-cli:ci"

  action-testing:
    name: Action Testing
    runs-on: ubuntu-latest
    needs:
      - container-build
    services:
      otel-server:
        image: "otel-cli:ci"
        env:
          SERVER: "true"
        ports:
          - 4317:4317
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Send a trace
        uses: ./
        with:
          otel-exporter-oltp-endpoint: otel-server:4317
          args: "otel-cli exec --service my-service --name 'curl google' curl https://google.com"
