---
name: Test Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  container-build:
    name: Build Container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tags: ${{ steps.meta.outputs.tags }}
      labels: ${{ steps.meta.outputs.labels }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4.3.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  action-testing:
    name: Action Testing
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    needs:
      - container-build
    services:
      otel-server:
        # Apparently env is not accessible from GHA services
        image: "${{ needs.container-build.outputs.tags }}"
        env:
          SERVER: "true"
        ports:
          - 4317:4317
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Send a trace
        uses: ./
        with:
          otel-exporter-oltp-endpoint: otel-server:4317
          args: "otel-cli exec --service my-service --name 'curl google' curl https://google.com"
