---
name: Test the Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action-testing:
    name: Action Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Start local server
        uses: ./
        # run otel-cli as a local OTLP server and print traces to your console
        with:
          args: "server tui &"

      - name: Send a trace
        uses: ./
        with:
          otel-exporter-oltp-endpoint: localhost:4317
          args: "otel-cli exec --service my-service --name 'curl google' curl https://google.com"
