---
name: Test the Action
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action-testing:
    name: Action Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Start local server
        uses: ./
        # run otel-cli as a local OTLP server and print traces to your console
        with:
          args: "server tui"

# # configure otel-cli to talk the the local server spawned above
# export OTEL_EXPORTER_OTLP_ENDPOINT=localhost:4317

# # run a program inside a span
# otel-cli exec --service my-service --name "curl google" curl https://google.com
